version: '3.7'
services:
  database:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    container_name: db-lab-postgres
    environment: 
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadminpassword
  db-lab-pgadmin4:
    image: stefantruehl/db-lab-pgadmin4:4.20-1
    ports:
      - "5050:5050"
    volumes:
      - type: bind
        source: ./exchange-folder
        target: /var/lib/pgadmin/storage/user_domain.com/exchange-folder
    environment: 
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=secretpassword
      - PGADMIN_ENABLE_TLS
      - PGADMIN_LISTEN_PORT=5050

      
volumes:
  exchange-folder:
      
  
